### ISSUE TITLE
Is is possible to run without lamba? 

### ISSUE THREAD

**Issue by mrPsycho** [yahoo/ariel#17]
Hi, to test how it works - is it possible to run without lambda?

**Comment by bastille** [comment]
Yes, I frequently do run Ariel outside of Lambda.  You can invoke it like a normal python application.  From the top level of the project:

`python3 -m ariel lambda -h`

If you're familiar enough with the code, you can also run the individual steps of the processing independently.

`python3 -m ariel -h`
